apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: demo
  namespace: argocd 
spec: 
  project: default
  repoURL: git@github.com:barnettet31/homelab.git
  path: demo
  targetRevision: main
destination: 
  server: https://kubernetes.default.svc
  namespace: default
syncPolicy: 
  automated: 
    prune: true
    selfHeal: true