apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      initContainers:
      - name: prepare-data-dir
        image: busybox:1.36.1
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Creating data directory structure..."
          mkdir -p /etc/linkding/data

          echo "Setting permissions..."
          chmod -R 777 /etc/linkding

          echo "Setting ownership..."
          chown -R 33:33 etc/linkding/data

          echo "Verifying directory structure and permissions:"
          ls -la /etc/linkding
          ls -la /etc/linkding/data
        securityContext:
          runAsUser: 0
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.39.0
          envFrom:
            - secretRef:
                name: linkding-container-env
          env:
            - name: DEBUG
              value: "False"
          ports:
            - containerPort: 9090
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
